name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: '${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        restic:
          - "0.12.1"
    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Publish to GitHub Container Registry
        env:
          REGISTRY: ghcr.io/stashed
          DOCKER_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
          USERNAME: 1gtm
        run: |
          docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}
          make release RELEASE=${{ matrix.restic }}

      - name: Publish to Docker Registry
        env:
          REGISTRY: stashed
          SRC_REG: ghcr.io/stashed
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          USERNAME: 1gtm
        run: |
          docker login --username ${USERNAME} --password ${DOCKER_TOKEN}
          make release RELEASE=${{ matrix.restic }}
